version: '2.28.1'
   
services:
  backend:
    build: 
     context: ./backend
    command: python manage runserver
    ports:
     - "8000:443"

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
      
volumes:
  react_build:
    
